services:
  ss-port8443:
    image: ghcr.io/shadowsocks/ssserver-rust
    command: ssserver -vv
    ports:
      - "8443:8388/tcp"
      - "8443:8388/udp"
    restart: always
    volumes:
      - ~/ss/config.json:/etc/shadowsocks-rust/config.json
    networks:
      - shadowsocks

  ss-port443:
    image: ghcr.io/shadowsocks/ssserver-rust
    command: ssserver -vv
    ports:
      - "443:8388/tcp"
      - "443:8388/udp"
    restart: always
    volumes:
      - ~/ss/config.json:/etc/shadowsocks-rust/config.json
    networks:
      - shadowsocks

networks:
  shadowsocks:
    name: shadowsocks
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: shadowsocks
