# optional: Mininal TLS version that the DoH and DoT server will use
minTlsServeVersion: 1.3
# if https port > 0: path to cert and key file for SSL encryption. if not set, self-signed certificate will be generated
certFile: /etc/lego/certificates/lego.crt
keyFile: /etc/lego/certificates/lego.key
#
upstream:
  default:
    - https://dns11.quad9.net/dns-query
    - https://cloudflare-dns.com/dns-query
upstreamTimeout: 5s

bootstrapDns:
  - upstream: https://dns11.quad9.net/dns-query
    ips:
    - 9.9.9.11
    - 149.112.112.11
    - 2620:fe::11
    - 2620:fe::fe:11
  - upstream: https://cloudflare-dns.com/dns-query
    ips:
    - 1.1.1.1

ports:
  dns: 53
  tls: 853
  #https: 26443
  http: 4000

blocking:
  blackLists:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  clientGroupsBlock:
    default:
      - ads

caching:
  minTime: 5m
  maxTime: 30m
  maxItemsCount: 0
  prefetching: false
  prefetchExpires: 2h
  prefetchThreshold: 5
  prefetchMaxItemsCount: 0
  cacheTimeNegative: 30m

log:
  level: info
  format: text
  timestamp: true
  privacy: false

queryLog:
  type: console
  target: /logs
  logRetentionDays: 7
  fields:
  - clientIP
  - question
  - duration

prometheus:
  enable: true
  path: /metrics


